### ISSUE TITLE
JWT 취약점

### ISSUE THREAD

**Issue by yeonfish6040** [jeamxn/dimigoin-pull-service#14]
로그아웃을 한 후 refresh 토큰이 만료되지 않음.

이를 이용해서 토큰을 탈취시 비록 사용자가 로그아웃 하더라도 XSS .. 등등을 이용하여 액세스 토큰과 refresh토큰을 탈취할시 해당 사용자로 로그인이 가능하게 된다. 학생들 대상으로는 해당 취약점이 문제가 되지는 않지만 금요귀가 신청시 reason을 쓰는 부분에서 XSS가 발생할 가능성이 있어 선생님 계정을 탈취할 수 있어 보인다.

이런 취약점이 있는 것으로 보입니다.

**Comment by yeonfish6040** [comment]
아 수정하겠습니다.
미들웨어에서 로그인 확인할때 토큰이 만료된 토큰인지 확인하는 과정이 없습니다.
그래서 로그인처리가 됩니다.

**Comment by jeamxn** [comment]
closed with pr

**Comment by jeamxn** [comment]
미들웨어에 없는거 맞음 ㅜㅜ

**Comment by jeamxn** [comment]
차피 [여기](https://github.com/jeamxn/dimigoin-pull-service/blob/main/src/app/auth/refresh/route.ts)에서 refresh 할 때 만료됐는지 확인하는 ㄱㅊ을듯
