### ISSUE TITLE
기상곡 관련 취약점 제보

### ISSUE THREAD

**Issue by sihyeokpark** [jeamxn/dimigoin-pull-service#22]
# 기상곡 영상의 썸네일, 제목, 링크 변조 가능 취약점
https://github.com/jeamxn/dimigoin-pull-service/blob/baa453ed839d9b98dee78169060800b0abf96fda/src/app/api/wakeup/put.ts#L56-L64
https://github.com/jeamxn/dimigoin-pull-service/blob/baa453ed839d9b98dee78169060800b0abf96fda/src/app/(login)/wakeup/list/page.tsx#L84-L90
`thumnail` url을 조작해서 CSRF 공격 가능 (물론 CSRF가 가능한 벡터는 찾아봐야함)
`id` 값을 조작해서 다른 영상인척하기 가능
그 외 `title` 등등도 조작 가능함

![image](https://github.com/jeamxn/dimigoin-pull-service/assets/56220973/f6085432-64a6-4709-9bca-d81875c0dfa0)

지금 이 영상도 클릭하면 다른 영상으로 접속됨
⇒ 이를 통해 멀쩡한 영상인척 둔갑하다 이상한 영상으로 redirect 될 수 있음

**Comment by sihyeokpark** [comment]
## 변조하는 과정
![image](https://github.com/jeamxn/dimigoin-pull-service/assets/56220973/5953fe37-0282-43b7-b12f-0d3b8d4407c6)
id를 위조함
![image](https://github.com/jeamxn/dimigoin-pull-service/assets/56220973/dc9cbe93-0b04-4b00-ac57-93a9ac991dfb)
정상적인 노래인것 같지만,
![image](https://github.com/jeamxn/dimigoin-pull-service/assets/56220973/bea028a1-7e97-4ab8-90a8-dc3995bddfbe)
접속하면 다른 영상으로 redirect됨

**Comment by jeamxn** [comment]
이거 정확혀 귀찮아서 대충 때려박았었음

**Comment by jeamxn** [comment]
해결해줄 시혁이~

**Comment by sihyeokpark** [comment]
ㅠㅠ 허접 시혁이는 못고쳐요

**Comment by yeonfish6040** [comment]
백단에서 페이로드의 아이디에 대한 동영상 제목과 페이로드의 동영상 제목을 비교하는 방식으로 페이로드를 검증하였습니다.

**Comment by jeamxn** [comment]
``https://www.youtube.com/oembed`` 

유튜브 api 사용해서 해결했습니당
